version: '3.8'

services:
  backend:
    build: ./server
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASS: postgres
      DB_NAME: vehicles_management
    networks:
      - app_network

  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: vehicles_management
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

  frontend:
    build: ./client   
    ports:
      - "4200:80"
    networks:
      - app_network

volumes:
  postgres_data:

networks:
  app_network:
    driver: bridge
